spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/assignment
    username: test
    password: test
    driverClassName: org.postgresql.Driver
  flyway:
    encoding: UTF-8
    baselineOnMigrate: true
  jpa:
    generate-ddl: false
    show-sql: true
  jackson:
    serialization:
      failOnEmptyBeans: false

rest:
  pageSize: 10
